name: ci
on:
  workflow_dispatch:
    inputs:
      fail:
        description: 'should a job fail?'
        required: true
        type: boolean
        default: false
  workflow_call:  
    inputs:
      fail:
        description: 'should a job fail?'
        required: true
        type: boolean
        default: false

jobs:
  job_A:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: asdf
        run: |
          cat file1.txt
  job_B:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: asdf
        run: echo "HERE"
      - name: maybe fail??
        if:  ${{ inputs.fail }} 
        run: exit -1
