name: ci
on:
  workflow_dispatch:
    inputs:
      fail:
        description: 'should a job fail?'
        required: true
        type: boolean
        default: false
  workflow_call:  
    inputs:
      fail:
        description: 'should a job fail?'
        required: true
        type: boolean
        default: false

jobs:
  job_A:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: asdf
        run: |
          cat file1.txt
          touch new-file.txt
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: new-file.txt
  job_B:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: asdf
        run: echo "HERE"
      - name: maybe fail??
        if:  ${{ inputs.fail }} 
        run: exit -1
  job_C:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0
    
      - uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: "Dockerfile.test"
          tags: my-test-image:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          
      - name: Run inside docker image
        uses: addnab/docker-run-action@v3
        with:
          image: my-test-image:latest
          run: |
            cat file1.txt