name: release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      new-version:
        required: true
        type: string

jobs: 

  intermediate:
    runs-on: ubuntu-latest
    outputs:
      new-sha: ${{ steps.asdf.outputs.new-sha }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: update version file and add tag
        id: asdf
        run: |
          git config --global user.name "the 'release' github action"
          git config --global user.email "you@example.com"

          echo ${{ inputs.version }} > version.txt
          git commit -am "${{ inputs.version }} released."
          git push
          git tag -f "v${{ inputs.version }}"
          git push origin "refs/tags/v${{ inputs.version }}"
          echo "new-sha=`git rev-parse HEAD`" >> "$GITHUB_OUTPUT"

  tag: # shows how to add a tag to the git repo
    runs-on: ubuntu-latest
    needs: intermediate    
    steps:
      - name: checkout
        uses: actions/checkout@v4
        #with:
        #  ref: ${{ needs.intermediate.outputs.new-sha }}

      - name: update the version file
        run: |
          git pull

          git config --global user.name "the 'release' github action"
          git config --global user.email "you@example.com"

          cat version.txt
          echo ${{ inputs.new-version }} > version.txt
          
          git commit -am 'update version'
          git push