name: release
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'is this an actual release?'
        required: true
        type: boolean
        default: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      fail: false
  package:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: step1
        run: echo "building some packages"
