name: release
on:
  workflow_dispatch:

jobs:
  release_A:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: call
        uses: ./.github/workflows/ci.yml
