name: release
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'is this an actual release?'
        required: true
        type: boolean
        default: false
      fail:
        description: 'should a job fail?'
        required: true
        type: boolean
        default: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      fail: ${{ inputs.fail }} 
  package:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: step1
        run: echo "building some packages"
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: ls
        run: ls
  tag:
    runs-on: ubuntu-latest
    needs: package
    if:  ${{ inputs.release }} 
    steps:
      - name: Create Git tag for PR
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/0.0.0-pr${{github.event.number}}",
              sha: context.sha
            })
